config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'
  resources :users, only: [:index, :show, :new, :create] do
    member do
      get :followings
      get :followers
      get :likes
    end
    collection do
      get :search
    end
  end
  
  resources :tecposts, only: [:show, :edit, :update, :create, :destroy] do
    member do
      get :remsgs
    end
  end
      
  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]
  
end

app/models/tecpost.rb
class Tecpost < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :user
  
  validates :title, presence: true, length: { maximum: 15 }
  validates :content, presence: true, length: { maximum: 255 }
  
  has_many :favorites,dependent: :destroy
  has_many :users, through: :favorites
  
  has_many :comments,dependent: :destroy
  has_many :users, through: :comments
  
  def remsg(tecpost)
      comments.find_or_create_by(tecpost_id: tecpost.id)
  end
  
  def unremsg(tecpost)
    comment = self.comments.find_by(tecpost_id: tecpost.id)
    comment.destroy if comment
  end

  def remsging?(tecpost)
    self.remsgs.include?(tecpost)
  end
end

app/controllers/tecposts_controller.rb
class TecpostsController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:edit,:update,:destroy]
  
  def show
    @tecpost = Tecpost.find(params[:id])
    @remsgs = @tecpost.comments.order(id: :desc).page(params[:page]).per(3)
    #@remsg = Comment.new
    @remsg = current_user.comments.build
    @remsg.tecpost_id = params[:id]
  end
  
  def edit
    @tecpost = Tecpost.find(params[:id])
  end
  
  def update
    @tecpost = Tecpost.find(params[:id])

    if @tecpost.update(tecpost_params)
      flash[:success] = 'メッセージを編集しました'
      redirect_to @tecpost
    else
      flash.now[:danger] = 'メッセージの編集は失敗しました'
      render :edit
    end
  end
  
  def create
    @tecpost = current_user.tecposts.build(tecpost_params)
    if @tecpost.save
      flash[:success] = 'メッセージを投稿しました。'
      redirect_to root_url
    else
      @tecposts = current_user.feed_tecposts.order(id: :desc).page(params[:page])
      flash.now[:danger] = 'メッセージの投稿は失敗しました。'
      render 'toppages/index'
    end
  end

  def destroy
    @tecpost.destroy
    flash[:success] = 'メッセージを削除しました。'
    redirect_back(fallback_location: root_path)
  end
  
  private
  
  def tecpost_params
    params.require(:tecpost).permit(:title, :content, :image)
  end
  
  def correct_user
    @tecpost = current_user.tecposts.find_by(id: params[:id])
    unless @tecpost
      redirect_to root_url
    end
  end
end

app/views/tecposts/_tecposts.html.erb
<ul class="list-unstyled">
  <% tecposts.each do |tecpost| %>
    <li class="media mb-3">
      <img class="mr-2 rounded" src="<%= gravatar_url(tecpost.user, { size: 50 }) %>" alt="">
      <div class="media-body">
        <div>
          <%= link_to tecpost.id, tecpost %> <span class="text-muted" >投稿者: <%= tecpost.user.name %> <%= tecpost.created_at %></span>
        </div>
        <div>
          <p class="mb-0"><%= tecpost.title %></p>
        
          <p class="mb-0 word-break"><%==h(tecpost.content).gsub(/\r\n|\r|\n/, "<br>") %></p>
          
          <p>
            <%=image_tag tecpost.image.url, class: 'myimg' if tecpost.image? %>
          </p>
      
        </div>
        <div>
          <% if current_user == tecpost.user %>
          <div class="mt-0 pb-2">
            <%= link_to "編集", edit_tecpost_path(tecpost), class: 'btn btn-primary btn-sm' %>
            <%= link_to "Delete", tecpost, method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-danger btn-sm' %>
          </div>
          <% end %>
          <%= render 'favorites/like_button', tecpost: tecpost %>
        </div>
      </div>
    </li>
  <% end %>
  <div class="pagination"></div>
  <%= paginate tecposts %>
</ul> 

app/views/tecposts/edit.html.erb
<h1 class="editpage">メッセージ編集ページ</h1>

<%= form_with(model: @tecpost, local: true) do |f| %>

<%= render 'layouts/error_messages', model: f.object %>

<div class="form-group">
  <%= f.label :title, 'タイトル' %>
  <%= f.text_field :title, class: 'form-control' %>
</div>
  
<div class="form-group">
  <%= f.label :content, 'メッセージ' %>
  <%= f.text_area :content, class: 'form-control', rows: 6 %>
</div>

<div class="field">  
    <%= f.label "画像をアップロード" %> 
    <%= f.file_field :image %>
</div>

 <%= f.submit '送信', class: 'btn btn-primary mt-2 mb-3' %>

<% end %>

<%= link_to '一覧に戻る', root_path %>

app/views/tecposts/show.html.erb
    <h1>メッセージ詳細ページ</h1>
    
      <div class="text-muted" >投稿者: <%= @tecpost.user.name %> <%= @tecpost.created_at %></div>
      
      <img class="mr-2 rounded" src="<%= gravatar_url(@tecpost.user, { size: 50 }) %>" alt="">
      
    <p><%= @tecpost.title %></p>
    <p><%==h(@tecpost.content).gsub(/\r\n|\r|\n/, "<br>") %></p>
    <p>
    <%=image_tag @tecpost.image.url, class: 'myimg' if @tecpost.image? %>
    </p>

  <h2 class="mt-4 pb-2 border-bottom">コメント一覧</h2>
  
  <% @remsgs.each do |remsg| %>
  
    <div class="text-muted" >投稿者: <%= @remsg.user.name %> <%= @tecpost.created_at %></div>
  
    <img class="mr-2 rounded" src="<%= gravatar_url(@remsg.user, { size: 50 }) %>" alt="">  
  
    <p><%==(remsg.content).gsub(/\r\n|\r|\n/, "<br>") %></p>
  
  <p>
  <%=image_tag remsg.image.url, class: 'myimg' if remsg.image? %>
  </p>
  
  <% if current_user == remsg.user %>
    <div class="mt-0 pb-2">
    <%= link_to "削除", comment_path(remsg.id), method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-danger btn-sm' %>
    </div>
  <% end %>

<% end %>
<%= paginate @remsgs %>

 
<%= form_with(model: @remsg, local: true) do |f| %>

<%= render 'layouts/error_messages', model: f.object %>

<%= hidden_field_tag :tecpost_id, @tecpost.id %>

<div class="form-group">
  <%= f.label :content, 'コメント' %>
  <%= f.text_area :content, class: 'form-control', rows: 4 %>
</div>

<div class="field">  
  <%= f.label "画像をアップロード" %> 
          <%= f.file_field :image %>
</div>

  <%= f.submit 'コメントする', class: 'btn btn-primary mt-2 mb-3' %>

<% end %>
 
<%= link_to '一覧に戻る', root_path %>